operator = "db_driver"
state = "stateless"
port = "50160"

[ProcessingConfig]
grpcServers = 1
[ProcessingConfig.API]
maxWorkers = 4
maxJobQueue = 10000

[ProcessingConfig.Input]
maxWorkers = 2
maxJobQueue = 10000

[[InputSchema]]
table = "testbuck"
[[InputSchema.Attributes]]
key = "attribute0"
type = "int"

[Evaluation]
tracing = false
logTimestamps = false
measureNotificationLatency = false
measureDataTransfer = false

[DatastoreConfig]
type = "s3"
endpoint = "http://127.0.0.1:8001"
logStreamEndpoint = "127.0.0.1:50001"
[DatastoreConfig.Credentials]
accessKeyID = "accessKey1"
secretAccessKey = "verySecretKey1"
