version: '3'
services:
  datastore-mv:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - ${PWD}/datastore/build/setup-lobsters.sh:/docker-entrypoint-initdb.d/setup.sh
      - ${PWD}/datastore/build/db-schema/schema-lobsters.sql:/opt/proteus-lobsters/schema-lobsters.sql
      - ${PWD}/datastore/dataset/small-mv.sql:/opt/proteus-lobsters/small-mv.sql
    ports:
      - 3306:3306
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]