version: '3'
services:
  datastore-proteus:
    image: datastore/proteus:latest
    networks:
      - proteus_net
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - ${PWD}/datastore/build/setup-proteus.sh:/docker-entrypoint-initdb.d/setup.sh
      - ${PWD}/datastore/build/db-schema/schema-proteus.sql:/opt/proteus-lobsters/schema-proteus.sql
      - ${PWD}/datastore/dataset/small.sql:/opt/proteus-lobsters/small.sql
      # - ${PWD}/datastore:/opt/proteus-lobsters
    ports:
      - 3307:3306
      - 50000:50000
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [ node.labels.datastore == true ]

networks:
  proteus_net:
    external: true
