# Use root/example as user/password credentials
version: '3.1'

services:
  dsdriver-0:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/dsdriver0.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

  dsdriver-1:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/dsdriver1.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true

  dsdriver-2:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/dsdriver2.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud1 == true

  index-0:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/global/index0.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

  index-1:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/global/index1.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true

  index-2:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/global/index2.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud1 == true

  router-0:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/global/router0.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

  router-1:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/global/router1.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true

  router-2:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/:/configs
    command: /configs/global/router2.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud1 == true

networks:
  qpu_graph:
  proteus_net:
    external: true
