# Use root/example as user/password credentials
version: '3.1'

services:
  ycsb:
    image: 127.0.0.1:5000/ycsb:${TAG_YCSB}
    #    image: ycsb/dev
    networks:
      - proteus_net
    environment:
      - TYPE=load
      - THREADS=1
      - EXECUTIONTIME=60
      - WARMUPTIME=20
      - CARDINALITY=10000
      - FIELDCOUNT=5
      - POOLSIZE=512
      - MONGOURL=mongodb://root:example@mongo2:27017/?replicaSet=rs0
      - MONGOHOST=mongo0
      - MONGOPORT=27017
      - PROTEUSHOST=index-0
      - PROTEUSPORT=50350
      - RECORDCOUNT=99000
      - INSERTSTART=66000
      - INSERTCOUNT=33000
      - QUERYPROPORTION=0
      - UPDATEPROPORTION=0
      - OUTPUT_FILE_NAME=out
    volumes:
      - /tmp:/ycsb
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud1 == true

# index:
#    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
#    networks:
#      - proteus_net
#    ports:
#      - 50350:50350
#    volumes:
#      - ${PWD}/configs:/configs
#    command: /configs/index.toml error
#    deploy:
#      restart_policy:
#        condition: none
#      placement:
#        constraints:
#          - node.labels.client == true

networks:
  qpu_graph:
  proteus_net:
    external: true
