# Use root/example as user/password credentials
version: '3.1'

services:
  cloudserver-0:
    image: dvasilas/cloudserver:latest
    networks:
      - proteus_net
    environment:
      - REMOTE_MANAGEMENT_DISABLE=1
      - S3BACKEND=file
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true

  mongo:
    image: mongo
    networks:
      - proteus_net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    placement:
      constraints:
        - node.labels.cloud == true

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    placement:
      constraints:
        - node.labels.cloud == true

  dsdriver:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs:/configs
    command: /configs/dsdriver.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true

  sum:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs:/configs
    command: /configs/index.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true