# Use root/example as user/password credentials
version: '3.1'

services:
  cloudserver-0:
    image: dvasilas/cloudserver:latest
    networks:
      - proteus_net
    ports:
      - 8000:8000
    environment:
      - REMOTE_MANAGEMENT_DISABLE=1
      - S3BACKEND=file
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=verySecretKey1
    volumes:
      - ${HOME}/volume/datastore/dataset/ycsb/data1_run:/usr/src/app/localData
      - ${HOME}/volume/datastore/dataset/ycsb/metadata1_run:/usr/src/app/localMetadata
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

  mongo:
    image: mongo
    networks:
      - proteus_net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      restart_policy:
        condition: none
      placement:
         constraints:
          - node.labels.client == true

  mongo-express:
    image: mongo-express
    networks:
      - proteus_net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

  dsdriver:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    volumes:
      - ${HOME}/volume/configs/ycsb:/configs
    command: /configs/dsdriver.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

  index:
    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
    networks:
      - proteus_net
    ports:
      - 50350:50350
    volumes:
      - ${HOME}/volume/configs/ycsb:/configs
    command: /configs/index.toml trace
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

networks:
  qpu_graph:
  proteus_net:
    external: true
