# Use root/example as user/password credentials
version: '3.1'

services:
  ycsb:
    image: 127.0.0.1:5000/ycsb:${TAG_YCSB}
    networks:
      - proteus_net
    environment:
     - TYPES=run
     - THREADS=${THREADS}
     - POOLSIZE=512
     - WORKLOAD=workloada
     - TABLE=ycsbbuck
     - EXECUTIONTIME=60
     - WARMUPTIME=20
     - PROTEUSHOST=cloudserver-0
     - PROTEUSPORT=8000
     - S3HOST=cloudserver-0
     - S3PORT=8000
     - S3ACCESSKEYID=accessKey1
     - S3SECRETKEY=verySecretKey1
     - RECORDCOUNT=1000
     - INSERTSTART=0
     - INSERTCOUNT=1000
     - QUERYPROPORTION=0
     - UPDATEPROPORTION=0
     - INSERTPROPORTION=1.0
     - CARDINALITY=50
     - OUTPUT_FILE_NAME=${LOGFILE}
    volumes:
      - /tmp:/ycsb
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.client == true

# index:
#    image: 127.0.0.1:5000/proteus-stateless:${TAG_QPU}
#    networks:
#      - proteus_net
#    ports:
#      - 50350:50350
#    volumes:
#      - ${PWD}/configs:/configs
#    command: /configs/index.toml error
#    deploy:
#      restart_policy:
#        condition: none
#      placement:
#        constraints:
#          - node.labels.client == true

networks:
  qpu_graph:
  proteus_net:
    external: true
