version: '3'
services:
  datastore:
    #image: dvasilas/proteus-lobsters:${TAG_DATASTORE}
    image: 127.0.0.1:5000/proteus-lobsters:${TAG_DATASTORE}
    networks:
      - proteus_net
    environment:
      - MYSQL_ROOT_PASSWORD=verySecretPwd
    volumes:
      - ${HOME}/volume/datastore/build/setup-proteus.sh:/docker-entrypoint-initdb.d/setup.sh
      - ${HOME}/volume/datastore/dataset/small.sql:/opt/proteus-lobsters/small.sql
      - ${HOME}/volume/datastore/dataset/med.sql:/opt/proteus-lobsters/med.sql
      - ${HOME}/volume/datastore/build/db-schema/schema-proteus.sql:/opt/proteus-lobsters/schema-proteus.sql
    ports:
      - 3307:3306
      - 50000:50000
    cap_add:
      - SYS_NICE
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == 1
          - node.labels.client == true

networks:
  proteus_net:
    external: true
