version: '3'
services:
  dsdriver:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - proteus_net
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
    command: /configs/lobsters/dsdriver.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_dsdriver == true

  sum-stories:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}volume/configs:/configs
    command: /configs/lobsters/sum-stories.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_sum == true

  sum-comments:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
    command: /configs/lobsters/sum-comments.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_sum == true

  join-stories:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
    command: /configs/lobsters/join-stories.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_join == true

  join-comments:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
    command: /configs/lobsters/join-comments.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_join == true

  router:
    image: dvasilas/proteus:${TAG_QPU}
    networks:
      - qpu_graph
    environment:
      - MYSQL_PASSWORD=verySecrectQPUPwd
    volumes:
      - ${HOME}/volume/configs:/configs
    ports:
      - 50450:50450
    command: /configs/lobsters/router.toml error
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.dc == eu
          - node.labels.placement_join == true

networks:
  qpu_graph:
  proteus_net:
    external: true
