operator = "router"
state = "stateless"
port = "50450"

[ProcessingConfig]
grpcServers = 1
[ProcessingConfig.API]
maxWorkers = 4
maxJobQueue = 10000

[ProcessingConfig.Input]
maxWorkers = 2
maxJobQueue = 10000

[[InputSchema]]
table = "ycsbbuck"
[[InputSchema.Attributes]]
key = "attribute0"
type = "int"

[Evaluation]
tracing = false
logTimestamps = false
measureNotificationLatency = false
measureDataTransfer = false

[[connections]]
address = "cache-0-2:50450"
local = "local"
[[connections]]
address = "cache-1-2:50450"
local = "local"
[[connections]]
address = "index-2:50350"
local = "local"
