operator = "db_driver"
state = "stateless"
port = "50150"

maxWorkers = 4
maxJobQueue = 10000

[[InputSchema]]
table = "votes"
[[InputSchema.Attributes]]
key = "story_id"
type = "int"
[[InputSchema.Attributes]]
key = "comment_id"
type = "int"
[[InputSchema.Attributes]]
key = "vote"
type = "int"

[[InputSchema]]
table = "stories"
[[InputSchema.Attributes]]
key = "id"
type = "int"
[[InputSchema.Attributes]]
key = "user_id"
type = "int"
[[InputSchema.Attributes]]
key = "title"
type = "string"
[[InputSchema.Attributes]]
key = "description"
type = "string"
[[InputSchema.Attributes]]
key = "short_id"
type = "string"

[[InputSchema]]
table = "comments"
[[InputSchema.Attributes]]
key = "id"
type = "int"
[[InputSchema.Attributes]]
key = "user_id"
type = "int"
[[InputSchema.Attributes]]
key = "story_id"
type = "int"
[[InputSchema.Attributes]]
key = "comment"
type = "string"

[Evaluation]
tracing = false
logTimestamps = true
measureNotificationLatency = true

[DatastoreConfig]
type = "mysql"
endpoint = "127.0.0.1:3307"
logStreamEndpoint = "127.0.0.1:50000"
DBName = "proteus_lobsters_db"
[DatastoreConfig.Credentials]
accessKeyID = "root"
secretAccessKey = "verySecretPwd"

[StateBackend]
endpoint = "127.0.0.1:3308"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "verySecrectQPUPwd"
