operator = "lobsters"
state = "stateless"
port = "50351"

[ProcessingConfig]
grpcServers = 1
[ProcessingConfig.API]
maxWorkers = 4
maxJobQueue = 10000

[ProcessingConfig.Input]
maxWorkers = 2
maxJobQueue = 10000

[Evaluation]
tracing = false
logTimestamps = true
measureNotificationLatency = true

[StateBackend]
endpoint = "127.0.0.1:3307"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "verySecretPwd"
