operator = "db_driver"
state = "stateless"
port = "50150"

[ProcessingConfig]
grpcServers = 1
[ProcessingConfig.API]
maxWorkers = 4
maxJobQueue = 10000

[ProcessingConfig.Input]
maxWorkers = 2
maxJobQueue = 10000

[[InputSchema]]
table = "ycsbbuck"
[[InputSchema.Attributes]]
key = "attribute0"
type = "int"

[Evaluation]
tracing = false
logTimestamps = false
measureNotificationLatency = false
measureDataTransfer = false

[DatastoreConfig]
type = "mongo"
endpoint = "mongodb://mongo0:27017/?replicaSet=rs0"
dbname = "cloudServer"
[DatastoreConfig.Credentials]
accessKeyID = "root"
secretAccessKey = "example"
