# Use root/example as user/password credentials
version: '3.1'

services:
  mongo-express-0:
    image: mongo-express
    networks:
      - proteus_net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo0
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.cloud == true

  # mongo-express-1:
  #   image: mongo-express
  #   networks:
  #     - proteus_net
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongo-1
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   deploy:
  #     restart_policy:
  #       condition: none
  #     placement:
  #       constraints:
  #         - node.labels.cloud == true

networks:
  proteus_net:
    external: true